<main>
    <div class="main container">
        <br>
        <h5>Food From Friends, Inc.</h5>
        <p>&nbsp;</p>
        <p><b>Privacy Policy</b></p>
        <p>Last Updated: October 31, 2017</p>
        <p>&nbsp;</p>
        <p>Food From Friends, Inc. (“Food From Friends”, “we” or “us”) provides this Privacy Policy to inform you of our policies and procedures regarding the collection, use and disclosure of personal information we receive from Members of https://www.foodfromfriends.co (the “Site”) and our application for mobile devices (the “Application”) .This Privacy Policy may be updated from time to time. This Privacy Policy applies only to information that you provide to us through the Site and Application.  We may update this Privacy Policy to reflect changes to our information practices. If we make any material changes we will notify you by email (sent to the e-mail address specified in your Food From Friends Account) or by means of a notice on the Site and Application prior to the change becoming effective. We encourage you to periodically review this page for the latest information on our privacy practices. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms of Service (<a href="<?php echo PUBLIC_ROOT . 'info/terms-of-service' ?>">https://www.foodfromfriends.co/info/terms-of-service</a>).<br>
        As used in this policy, the terms “using” and “processing” information include using cookies on a computer, subjecting the information to statistical or other analysis and using or handling information in any way, including, but not limited to collecting, storing, evaluating, modifying, deleting, using, combining, disclosing and transferring information within our organization or among our affiliates within the United States or internationally.</p>
        <p>International Transfer of Information<br>
        IF YOU ARE LOCATED OUTSIDE THE UNITED STATES AND CHOOSE TO PROVIDE INFORMATION TO US, FOOD FROM FRIENDS TRANSFERS PERSONAL INFORMATION TO THE UNITED STATES AND PROCESSES IT THERE. YOUR CONSENT TO THIS PRIVACY POLICY FOLLOWED BY YOUR SUBMISSION OF SUCH INFORMATION REPRESENTS YOUR AGREEMENT TO THAT TRANSFER. YOUR INFORMATION MAY BE TRANSFERRED TO – AND MAINTAINED ON – COMPUTERS LOCATED OUTSIDE OF YOUR STATE, PROVINCE, COUNTRY OR OTHER GOVERNMENTAL JURISDICTION WHERE THE PRIVACY LAWS MAY NOT BE AS PROTECTIVE AS THOSE IN YOUR JURISDICTION.<br>
        Automatically Record Information<br>
        When you visit the Site and Application, whether as a non-registered user or Member just browsing (any of these, an “Food From Friends User”), our servers automatically record information that your browser sends whenever you visit a website (“Log Data”). This Log Data may include information such as your computer’s Internet Protocol (“IP”) address, browser type or the webpage you were visiting before you came to our Site and Application, pages of our Site and Application that you visit, the time spent on those pages, information you search for on our Site and Application, access times and dates, and other statistics. We use this information to monitor and analyze use of the Site, Application and the Service and for the Site and Application’s technical administration, to increase our Site and Application’s functionality and user-friendliness, and to better tailor our Site and Application to our visitors’ needs. We also use this information to verify that visitors to the Site meet the criteria required to process their requests. We do not treat Log Data as Personal Information or use it in association with other Personal Information, though we may aggregate, analyze and evaluate such information for the same purposes as stated above regarding other Non-Identifying Information.<br>
        Use and Collection of Information<br>
        Our primary goals in collecting information are to provide and improve our Site, Application, services, features and content, to administer your use of the Site and Application (together, the “Service”) and to enable Members to enjoy and easily navigate the Site and Application.<br>
        Children Policy<br>
        The Site and Application are not directed to individuals under 18. We do not knowingly collect personally identifiable information from children under 18. If a parent or guardian becomes aware that his or her child has provided us with Personal Information without their consent, he or she should contact us at info@Food From Friends.com. If we become aware that a child under 18 has provided us with Personal Information, we will delete such information from our files.<br>
        Personally Identifiable Information<br>
        When you register with us through the Site or Application and become a Member and when you choose to post a Listing or request a Food Listing, or when you wish to contact another Member, we will  ask you for personally identifiable information. This refers to information about you that can be used to contact or identify you (“Identity Information”). Identity Information includes, but is not limited to, your name, phone number, email address, social security number (SSN), and home postal address, but does not include your credit card number or billing information. In order to process some of your transactions through the Site and Application, we may also ask for your credit card number and other billing information (“Billing Information”) (Identity Information and Billing Information together, “Personal Information”). If the address of a Listing you post matches that of your credit card billing address, that address would be considered Identity Information. Some Personal Information is required, like your name and email address, and other Personal Information is optional, like your date of birth. We reserve the right to require address confirmation for Food Listings included in Listings. If we require such confirmation, we will send a code via postal mail to the address contained in a Listing and ask you to enter the code via the Site, Application and Service in order to confirm the address of the Food Listing included in the applicable Listing. We use your Personal Information to provide the Service and administer your inquiries.<br>
        We collect Personal Information in connection with your registration to join the Service. You can register to join via the Site or Application by completing the required forms.<br>
        We also collect the other information that you provide as part of registration and the administration and personalization of your Food From Friends Account profile (e.g., without limitation, zip code (on its own) and individual preferences or demographic information) (“Non-Identifying Information”).<br>
        We use your Personal Information (in some cases, in conjunction with your Non-Identifying Information) mainly to provide the Service, complete your transactions, and administer your inquiries.<br>
        Certain Non-Identifying Information would be considered a part of your Personal Information if it were combined with other identifiers (for example, combining your zip code with your street address) in a way that enables you to be identified. But the same pieces of information are considered Non-Identifying Information when they are taken alone or combined only with other non-identifying information (for example, your demographic information). We may combine your Personal Information with Non-Identifying Information and aggregate it with information collected from other Food From Friends Users (defined below) to attempt to provide you with a better experience, to improve the quality and value of the Service and to analyze and understand how our Site, Application and Service are used. We may also use the combined information without aggregating it to serve you specifically, for instance to deliver a product to you according to your preferences or restrictions.<br>
        We also use your Personal Information to contact you with Food From Friends newsletters, marketing or promotional materials and other information that may be of interest to you. If you decide at any time that you no longer wish to receive such communications from us, please follow the unsubscribe instructions provided in any of the communications or update your “Notifications” information. (See “Changing or Deleting Information,” below.) Please note that we may also use your Personal Information to contact you with information related to your use of the Service; you may not opt out of these notifications.<br>
        Messaging Via a Food From Friends Account<br>
        As part of the Service, Food From Friends Members may communicate with other Food From Friends Members through use of the “Messaging” feature on the Site and Application.<br>
        Emailing Via a Food From Friends Account<br>
        If you choose to use our referral service to ask a friend for a recommendation, we will ask you for your friend’s email address. We will automatically send your friend a one-time email inviting him or her to visit the site. Food From Friends stores this information for the sole purpose of sending this one-time email.<br>
        Your friend may contact us at foodfromfriendsco@gmail.com to request that we remove this information from our database.<br>
        You can import contacts from your email account address request to invite them to send you a recommendation. We collect, but do not store, the username and password for the email account you wish to import your contacts from and will only use it for that purpose only.<br>
        Cookies<br>
        Like many websites, we use “cookies” to collect information. A cookie is a small data file that we transfer to your computer’s hard disk for record-keeping purposes. We use cookies for two purposes. First, we utilize persistent cookies to save your login information for future logins to the Site and Application. Second, we utilize session ID cookies to enable certain features of the Site and Application, to better understand how you interact with the Site and Application and to monitor aggregate usage by Food From Friends Users and web traffic routing on the Site and Application. Unlike persistent cookies, session cookies are deleted from your computer when you log off from the Site, Application and Service and then close your browser.You can instruct your browser, by changing its options, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you may not be able to use all portions of the Site or Application or all functionality of the Service.<br>
        Phishing<br>
        Identity theft and the practice currently known as “phishing” are of great concern to Food From Friends. Safeguarding information to help protect you from identity theft is a top priority. We do not and will not, at any time, request your credit card information, your Food From Friends Account ID, login password, or national identification numbers in a non-secure or unsolicited e-mail or telephone communication. For more information about phishing, visit the Federal Trade Commission’s website at http://www.ftc.gov.<br>
        Information Sharing and Disclosure<br>
        Overview<br>
        The Site, Application and Service can be used to facilitate the listing and requesting of Food Listings. Listings for such Food Listings are made available via the Site, Application and Service by Growers. Listings posted by Growers, ratings and reviews of Growers and Locavores, and the Profile Information (as defined below) of Growers and Locavore, are visible to any Food From Friends Users.<br>
        Food From Friends Members and Users<br>
        When you create a Food From Friends Account, we will set up a Food From Friends Account profile page for you. Your Food From Friends Account profile page will include your first name. You can select the other items of Personal Information that you wish to be included in your Food From Friends Account profile page – including, but not limited to, a profile picture, and a biography and links to your Listings, if applicable (together, your “Profile Information”). We will display your Profile Information in your Food From Friends Account profile page publicly via the Site and Application, and, with your prior permission. Any information you choose to provide as part of your Profile Information will be publicly visible to all Food From Friends Users and consequently should reflect how much you want other Food From Friends Users to know about you. We recommend that you guard your anonymity and sensitive information and we encourage members to think carefully about what information about themselves they disclose in their profile pages. You can review and revise your Profile Information at any time.<br>
        Listings<br>
        If you post a Listing, we may publish that Listing publicly via the Site and Application.. We may also display the geographical location of your Listing in the form of a map so that potential Locavores can see the general area and neighborhood of your Listing, but your actual street address will not be disclosed until you enter into a confirmed transaction with another Member.<br>
        If you make a request via the Site, Application and Service, Food From Friends will share the following information about you with the applicable Grower: (i) your first and last name, (ii) a link to your Food From Friends Account profile page.  All of this information will enable the Grower to decide whether to confirm or reject your requesting. When a Grower confirms a requesting we will share pieces of the Grower’s Identify Information, including, but not limited to, full name, the Food Listing’s address, with the applicable Locavore selected by the Grower and we will share pieces of the Locavore’s Identify Information with the Grower, including, but not limited to, first name and  last name so that the Locavore and Grower may contact one another directly. In no event is a Locavore’s Billing Information shared with a Grower.<br>
        Service Providers<br>
        We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Site and Application-related services (e.g., without limitation, maintenance services, database management, web analytics, fraud detection services relating to the activity of Food From Friends Users and improvement of the Site and Application’s features) or to assist us in analyzing how our Site, Application and Service are used. These third parties may have access to your Personal Information; if they do, this access is only so that they may perform these tasks on our behalf and they are obligated not to disclose or use it for any other purpose. We may also provide Personal Information to our business partners or other trusted entities for the purpose of providing you with information on goods or services we believe will be of interest to you. You can, at any time, opt out of receiving such communications. Third party vendors, including Google, use cookies to serve ads based on an Food From Friends User’s prior visits to Food From Friends. You can disable these specific cookies that track prior visits for the sake of follow-up advertising by opting out at http://www.google.com/privacy_ads.html.<br>
        Aggregate Information and Non-Identifying Information<br>
        We may share aggregated information that does not include Personal Information and we may otherwise disclose Non-Identifying Information and Log Data with third parties for industry analysis, demographic profiling and other purposes. Any aggregated information shared in these contexts will not contain your Personal Information.<br>
        Compliance with Laws and Law Enforcement; Guarantee Program<br>
        Food From Friends cooperates with government and law enforcement officials and private parties to enforce and comply with the law. We will disclose any information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate to respond to claims and legal process (including but not limited to subpoenas), to protect the property and rights of Food From Friends or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, any illegal, unethical or legally actionable activity.<br>
        We will disclose any information about you to government or law enforcement officials and to our insurance services providers as we, in our sole discretion, believe necessary or appropriate, to protect the property and rights of Food From Friends or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, any illegal, unethical or legally actionable activity.<br>
        Changing or Deleting Your Information<br>
        All Members may review, update, correct or delete the Personal Information in their registration profile by contacting us at foodfromfriendsco@gmail.com or editing the relevant part of their profile. If you would like us to cancel your Food From Friends Account, please contact us or select the “Cancel Account” feature of the Service and we will attempt to accommodate your request if we do not have any legal obligation or a legitimate business reason to retain the information contained in your Food From Friends Account. Please note that, if you cancel your Food From Friends Account, any reviews you have posted via the Site and Application will remain publicly viewable via the Site and Application. Please see below for privacy contact information.<br>
        Business Transfers<br>
        Food From Friends may sell, transfer or otherwise share some or all of its assets, including your Personal Information, in connection with a merger, acquisition, reorganization or sale of assets or in the event of bankruptcy.<br>
        Security<br>
        Food From Friends is very concerned with safeguarding your information. When you enter sensitive information (such as credit card number and/or social security number) on our registration or order forms, we encrypt that information using secure socket layer technology (SSL). We follow generally accepted industry standards to protect the Personal Information submitted to us, both during transmission and once we receive it. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, we cannot guarantee its absolute security. If you have any questions about security on our Site and Application, you can contact us at foodfromfriendsco@gmail.com.<br>
        We will make any legally required disclosures of any breach of the security, confidentiality, or integrity of your unencrypted electronically stored “personal data” (as defined in applicable state statutes on security breach notification) to you via email or conspicuous posting on the Site and Application in the most expedient time possible and without unreasonable delay, insofar as consistent with (i) the legitimate needs of law enforcement or (ii) any measures necessary to determine the scope of the breach and restore the reasonable integrity of the data system.<br>
        Links to Other Websites<br>
        Our Site and Application contain links to other websites. If you choose to visit an advertiser by “clicking on” a banner ad or other type of advertisement, or click on another third party link, you will be directed to that third party’s website. The fact that we link to a website or present a banner ad or other type of advertisement is not an endorsement, authorization or representation of our affiliation with that third party, nor is it an endorsement of their privacy or information security policies or practices. We do not exercise control over third party websites. These other websites may place their own cookies or other files on your computer, collect data or solicit personal information from you. Other websites follow different rules regarding the use or disclosure of the personal information you submit to them. We encourage you to read the privacy policies or statements of the other websites you visit.</p>
        <p>Testimonials<br>
        With your consent we may post your testimonial on the Site and Application along with your name. If you want your testimonial removed please contact us at foodfromfriends@gmail.com.</p>
        <p>Contacting Us<br>
If you have any questions about this Privacy Policy, please contact Food From Friends at foodfromfriendsco@gmail.com.</p>
    </div>
</main>