<main>
    <div class="main container">
        <br>
        <h5>Food From Friends, Inc.</h5>
        <p>&nbsp;</p>
        <p><b>Terms &amp; Conditions </b></p>
        <p>Last Updated: December 1, 2017</p>
        <p>&nbsp;</p>
        <p>Food From Friends, Inc. (hereafter referred to as “Food From Friends”, “us”,”we”, or “our”) provides an marketplace that is online and that connects Food producers and Food consumers (collectively, the “Services”), which Services are accessible at https://www.foodfromfriends.co (collectively, the “Site”), and as an application that is for mobile devices (“Application”). By visiting and using the Site or Application, you agree to be legally bound by and comply with the terms and conditions of these Terms of Service (“Terms”), whether or not you become a Member or a registered user of the Services. These Terms govern your access to and use of the Site, Application, Services and all Collective Content (defined below), and your participation in referral and other promotion programs undertaken by us from time to time (“Referral Programs”), and constitute a binding legal agreement between you and Food From Friends. Please read carefully these Terms and our Privacy Policy, which may be found at <a href="<?= PUBLIC_ROOT . 'info/privacy-policy'; ?>">https://www.foodfromfriends.co/info/privacy-policy/</a>, and which is incorporated by reference into these Terms. If you do not agree to these Terms, you have no right to obtain information from or otherwise use the Site, Application or Services. Failure to use the Site and Application in accordance with these Terms may subject you to civil and criminal penalties.</p>
        <p>&nbsp;</p>
        <p>Certain areas of the Site and Application (and your access to or use of certain aspects of the Services or Collective Content) may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between these Terms and terms and conditions posted for a specific area of the Site, Application, Services, or Collective Content, the latter terms and conditions will take precedence with respect to your use of or access to that area of the Site, Application, Services, or Collective Content.</p>
        <p>YOU ACKNOWLEDGE AND AGREE THAT, BY ACCESSING OR USING THE SITE, APPLICATION OR SERVICES OR BY DOWNLOADING OR POSTING ANY CONTENT FROM OR ON THE SITE, VIA THE APPLICATION OR THROUGH THE SERVICES, OR BY PARTICIPATING IN ANY REFERRAL PROGRAM, YOU ARE INDICATING THAT YOU HAVE READ, AND THAT YOU UNDERSTAND AND AGREE TO BE BOUND BY THESE TERMS, WHETHER OR NOT YOU HAVE REGISTERED WITH THE SITE AND APPLICATION. IF YOU DO NOT AGREE TO THESE TERMS, THEN YOU HAVE NO RIGHT TO ACCESS OR USE THE SITE, APPLICATION, SERVICES, OR COLLECTIVE CONTENT OR TO PARTICIPATE IN ANY REFERRAL PROGRAM.</p>
        <p>If you accept or agree to these Terms on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to these Terms and, in such event, “you” and “your” will refer and apply to that company or other legal entity.</p>
        <p>&nbsp;</p>
        <p><b>Eligibility</b></p>
        <p>The Site, Application and Services are intended solely for persons who are 18 or older. By accessing or using the Site, Application or Services you represent and warrant that you are 18 or older.</p>
        <p><b>How the Site, Application and Services Work</b></p>
        <p>The Site, Application and Services can be used to locate and request Item from Growers. Such Food items are included on the Site, Application and Services by Growers. You may view Food as an unregistered visitor to the Site, Application and Services; however, if you wish to request Food or provide Items of Food, you must first register to create a Food From Friends Account (defined below).</p>
        <p>As stated above, Food From Friends makes available a marketplace for Growers and Locavores to connect online. Food From Friends is not an owner or operator of food establishments, including, but not limited to, a grocery store. Food From Friends does not grow or provide food for Growers. Food From Friends’s role is solely to facilitate the availability of Food. Similarly, Food From Friends is not a contracting agent or representative of any Grower. Instead, Food From Friends’s role is solely to facilitate the availability of the Site, Application and Services for Members and to provide services related thereto.</p>
        <p>PLEASE NOTE THAT, AS STATED ABOVE, THE SITE, APPLICATION AND SERVICES ARE INTENDED TO BE USED ONLY TO FACILITATE THE REQUEST OF FOOD. FOOD FROM FRIENDS CANNOT AND DOES NOT CONTROL THE CONTENT CONTAINED IN ANY FOOD AND THE CONDITION, LEGALITY OR SUITABILITY OF ANY FOOD. FOOD FROM FRIENDS IS NOT RESPONSIBLE FOR AND DISCLAIMS ANY AND ALL LIABILITY RELATED TO ANY AND ALL FOOD. ACCORDINGLY, ANY REQUESTS WILL BE MADE AT THE LOCAVORE’S OWN RISK.</p>
        <p><b>Account Registration</b></p>
        <p>In order to request Food or provide Items of Food, and In order to access certain features of the Site and Application, you must register to create an account (“Food From Friends Account”) and become a Member. You may register to join the Services directly via the Site or Application. &nbsp;</p>
        <p>You agree to provide current, accurate, and complete information during the registration process and to update such information to keep it accurate, current and complete. You may not have more than one (1) active Food From Friends Account. Food From Friends reserves the right to suspend or terminate your Food From Friends Account and your access to the Site, Application and Services if you create more than one (1) Food From Friends Account or if any information provided during the registration process or thereafter proves to be inaccurate, not current or incomplete. You are responsible for safeguarding your password. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your Food From Friends Account, whether or not you have authorized such activities or actions.</p>
        <p><b>Modification</b></p>
        <p>Food From Friends reserves the right, at its sole discretion, to modify the Site, Application or Services or to modify these Terms, including the Service Fees, at any time and without prior notice. If we modify these Terms, we will post the modification on the Site or via the Application or may provide you with notice of the modification. We will also update the “Last Updated Date” at the top of these Terms. By continuing to access or use the Site, Application or Services after we have posted a modification on the Site or via the Application or have provided you with notice of a modification, you are indicating that you agree to be bound by the modified Terms. If the modified Terms are not acceptable to you, your only recourse is to cease using the Site, Application and Services.</p>
        <p><b>No Endorsement</b></p>
        <p>Food From Friends does not endorse any Members, any Food or any Member Content. In addition, although these Terms require Members to provide accurate information, we do not attempt to confirm, and do not confirm, any Member’s purported identity. You are responsible for determining the identity and suitability of others who you contact via the Site, Application and Services. We will not be responsible for any damage or harm resulting from your interactions with other Members. By using the Site, Application or Services, you agree that any legal remedy or liability that you seek to obtain for actions or omissions of other Members or other third parties will be limited to a claim against the particular Members or other third parties who caused you harm and you agree not to attempt to impose liability on, or seek any legal remedy from Food From Friends with respect to such actions or omissions. Accordingly, we encourage you to communicate directly with other Members on the Site and Services regarding any Item.</p>
        <p><b>Food</b></p>
        <p>As a Member, you may create Items of Food. To this end, you will be asked a variety of questions about the Food to be listed, including, but not limited to, the weight, quantity, type, and pricing and related rules and financial terms. In order to be featured in Items via the Site, Application and Services, all Food &nbsp;must have valid physical addresses. Food will be made publicly available via the Site, Application and Services. Other Members will be able to request your Food via the Site, Application and Services based upon the information provided in your Item. You understand and agree that once a Locavore requests a Grower’s Food, the price for such request may not be altered.</p>
        <p>You acknowledge and agree that you are solely responsible for any and all Food you post. Accordingly, you represent and warrant that any Food you list and the Locavore’s request of Food you list (i) will not breach any agreements you have entered into with any third parties, (ii) will (a) be in compliance with all applicable laws, Tax requirements, and rules and regulations that may apply to any Food included in a Item, including, but not limited to, zoning laws, health laws, license laws and any other applicable laws governing properties and food and (b) not conflict with the rights of third parties; and (iii) agree not to invite any persons other than Locavores to an Exchange of Food. </p>
        <p>Please note that Food From Friends assumes no responsibility for a Grower’s compliance with any applicable laws, rules and regulations, or a Grower’s failure to comply with the aforesaid covenants.</p>
        <p>You understand and agree that Food From Friends does not act as an insurer or as a contracting agent for, or representative of, you as a Grower, and if a Locavore requests your Food and a Locavore, or another individual, consumes your Food, any agreement you enter into with such Locavore is between you and the Locavore, or other individual, and Food From Friends is not a party thereto. Notwithstanding the foregoing, Food From Friends serves as the limited authorized payment collection agent of the Grower for the purpose of accepting, on behalf of the Grower, payments from Locavores of such amounts stipulated by the Grower.</p>
        <p>Please note that Food From Friends reserves the right, at any time and without prior notice, to remove or disable access to any Item for any reason, including Food that Food From Friends, in its sole discretion, considers to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Site, Application or Services.</p>
        <p>When you create a Item you may also choose to include certain requirements which must be met by the Members who are eligible to request your Food, including, but not limited to, requiring Members to have a profile picture or verified phone number, in order to request your Food. Any Member wishing to request Food included in Food with such requirements must meet these requirements.</p>
        <p>If you are a Grower you acknowledge and agree that, as a Grower, you are responsible for your own acts and omissions and are also responsible for the acts and omissions of any individuals who your are to participate in an Exchange of Food at your confirmation.</p>
        <p>Food From Friends recommends that Growers obtain appropriate insurance for their Items. Please review any insurance policy that you may have for your Food carefully, and in particular please make sure that you are familiar with and understand any exclusions to, and any deductibles that may apply for, such insurance policy, including, but not limited to, whether or not your insurance policy will cover the actions or inactions of persons (including the Locavores and any individuals the Locavores invites to the Exchange of Food, if applicable) while at your &nbsp;Exchange of Food.</p>
        <p><b>requests and Financial Terms for Growers</b></p>
        <p>If you are a Grower and a Locavore requested your Food &nbsp;via the Site, Application and Services, you will be required to either confirm or reject the request within <b>24 hours</b> of when the request is requested (as determined by Food From Friends in its sole discretion) or the request will be automatically cancelled. When a Food is requested via the Site, Application and Services, we will share with you (i) the first and last name of the Locavore who has requested the request, and (ii) a link to the Locavore’s Food From Friends Account profile page. If you are unable to confirm or decide to reject a request of Food within such 24 hour period, any amounts collected by Food From Friends for the requested request will be refunded to the applicable Locavore’s credit card and any pre-authorization of such credit card will be released.</p>
        <p>When you confirm a Food requested by a Locavore, Food From Friends will send you an email, text message or message via the Application confirming such request, depending on the selections you make via the Site, Application and Services. </p>
        <p>The fees displayed in each Item are comprised of the Food Fees (defined below) and the Service Fees (defined below.) Where applicable, Taxes may be charged in addition to the Food Fees and Service Fees. The Food Fees, the Service Fees and applicable Taxes are collectively referred to in these Terms as the “Total Fees”. The amounts due and payable by a Locavore solely relating to a Grower’s Food are the “Food Fees”. Please note that it is the Grower and not Food From Friends which determines the Food Fees. The Food Fee may include a delivery fee, at the Grower’s discretion. Food From Friends charges a fee to Locavores based upon a percentage of applicable Food Fees, which are the “Locavores Fees”. The Locavores Fees are added to the Food Fees to calculate the Total Fees (which will also include applicable Taxes) displayed in the applicable Item. Food From Friends will collect the Total Fees at the time of Food request confirmation (i.e. when the Grower confirms the Food request within 24 hours of the request) and will remit the Food Fees (less Grower Fees (as defined below)) to the Grower within 24 hours of when the Locavore receives Food through the Exchange of Food. </p>
        <p>Each Grower hereby appoints Food From Friends as the Grower’s limited payment collection agent solely for the purpose of accepting the Food Fees from Locavores.</p>
        <p>Each Grower agrees that payment made by a Locavore through Food From Friends, shall be considered the same as a payment made directly to the Grower, and the Grower will make the Food available to the Locavore in the agreed-upon manner as if the Grower has received the Food Fees. Each Grower agrees that Food From Friends may, in accordance with the cancellation policy selected by the Grower and reflected in the relevant item, (i) permit the Locavore to cancel the request and (ii) refund to the Locavore that portion of the Food Fees specified in the applicable cancellation policy. Each Grower understands that Food From Friends accepts payments from Locavores as the Grower’s limited payment collection agent and that Food From Friends’s obligation to pay the Grower is subject to and conditional upon successful receipt of the associated payments from Locavores. Food From Friends does not guarantee payments to Growers for amounts that have not been successfully received by Food From Friends from Locavores. In accepting appointment as the limited authorized agent of the Grower, Food From Friends assumes no liability for any acts or omissions of the Grower. </p>
        <p>Please note that Food From Friends does not currently charge fees for the creation of Items. However, you acknowledge and agree that Food From Friends reserves the right, in its sole discretion, to charge you for and collect fees from you for the creation of Items. Please note that Food From Friends will provide notice of any Food fee collection via the Site, Application and Services, prior to implementing such a Item fee feature.</p>
        <p><b>Requests and Financial Terms for Locavores</b></p>
        <p>The Growers, not Food From Friends, are solely responsible for honoring any confirmed requests and making available any Food reserved through the Site, Application and Services. If you, as a Locavore, choose to enter into a transaction with a Grower for the request of Food, you agree and understand that you will be required to enter into an agreement with the Grower and you agree to accept any terms, conditions, rules and restrictions associated with such Food imposed by the Grower. You acknowledge and agree that you, and not Food From Friends, will be responsible for performing the obligations of any such agreements, and Food From Friends is not a party to such agreements and disclaims all liability arising from or related to any such agreements.</p>
        <p>Food will specify the Total Fees. As noted above, the Grower is required to either confirm or reject the request within 24 hours of when the Food is requested (as determined by Food From Friends in its sole discretion) or the requested request will be automatically cancelled. If a Food request is cancelled (i.e. not confirmed by the applicable Grower), any amounts collected by Food From Friends will be refunded to such Locavore, depending on the selections the Locavore makes via the Site and Application, and any pre-authorization of such Locavore’s credit card will be released, if applicable.</p>
        <p>You agree to pay Food From Friends for the Total Fees for any Food requested in connection with your Food From Friends Account if such Food requests are confirmed by the applicable Grower. In order to establish a request pending the applicable Grower’s confirmation of your Food request, you understand and agree that Food From Friends reserves the right, in its sole discretion, to (i) obtain a pre-authorization via your credit card for the Total Fees or (ii) charge your credit card a nominal amount, not to exceed one dollar ($1) to verify your credit card. Once Food From Friends receives confirmation of your request from the applicable Grower, Food From Friends will collect the Total Fees in accordance with the terms and conditions of these Terms and the pricing terms set forth in the applicable Food. Please note that Food From Friends cannot control any fees that may be charged to a Locavore by his or her bank related to Food From Friends’s collection of the Total Fees, and Food From Friends disclaims all liability in this regard.</p>
        <p>In connection with your request, you will be asked to provide customary billing information such as name, billing address and credit card information either to Food From Friends or its third party payment processor. You agree to pay Food From Friends for any confirmed requests made in connection with your Food From Friends Account in accordance with these Terms by one of the methods described on the Site or Application – e.g. by Stripe or credit card. You hereby authorize the collection of such amounts by charging the credit card provided as part of requesting the request, either directly by Food From Friends or indirectly, via a third party online payment processor or by one of the payment methods described on the Site or Application. If you are directed to Food From Friends’s third party payment processor, you may be subject to terms and conditions governing use of that third party’s service and that third party’s personal information collection practices. Please review such terms and conditions and privacy policy before using the services. Once your confirmed request transaction is complete you will receive a confirmation email summarizing your confirmed request.</p>
        <p><b>Service Fees</b></p>
        <p>In consideration for providing the Services, Food From Friends collects service fees from Growers and Locavores (“Service Fees”). Service Fees are made up of two (2) components: (i) Locavore Fees and (ii) a fee that is charged to the Grower based upon a percentage of the amount of the Food Fees (“Grower Fees”). Where applicable, Taxes may also be charged in addition to the Grower Fees. Grower Fees are deducted from the Food Fees before remitting the Food Fees to the Grower, within 24 hours of when the Locavore receives Food. Locavore Fees are, as noted above, included in the Total Fees.</p>
        <p>Balances will be remitted to Growers via Stripe, direct deposit or other payment methods described on the Site or via the Application, in USD, depending upon the selections the Grower makes via the Site, Application and Services. Except as otherwise provided herein, Service Fees are non-refundable.</p>
        <p><b>General Request Information and Financial Terms</b></p>
        <p><b>Cancellations and Refunds</b></p>
        <p>If, as a Locavore, you cancel your requested Food before the requested Food is confirmed by a Grower, Food From Friends will refund any Food Fees collected for such request within a commercially reasonable time. If, as a Locavore, you wish to cancel a request &nbsp;made via the Site which has been confirmed by the Grower, Application and Services, the cancellation policy of the Grower contained in the applicable Food will apply to such cancellation.</p>
        <p>If a Grower cancels a confirmed request made via the Site, Services, and Application, (i) Food From Friends will refund the Total Fees for such request to the applicable Locavore within a commercially reasonable time of the cancellation. If a Grower cancelled a confirmed request and you, as a Locavore, have not received an email or other communication from Food From Friends, please contact Food From Friends at <a href="mailto:foodfromfriendsco@gmail.com">foodfromfriendsco@gmail.com</a>.</p>
        <p><b>Payment Processing Errors</b></p>
        <p>We will take steps to rectify any payment processing errors that we become aware of. These steps may include crediting or debiting (as appropriate) the same payment method used for the original payout to or payment by you, so that you end up receiving or paying the correct amount.</p>
        <p><b>Damage to Exchange of Food Location</b></p>
        <p>As a Member, you are responsible for treating the Exchange of Food location in &nbsp;a respectful manner. You acknowledge and agree that, as a Member, you are responsible for your own acts and omissions and are also responsible for the acts and omissions of any individuals who you invite to, or otherwise provide access to, the Exchange of Food. In the event that a Member claims otherwise and provides evidence of damage, including but not limited to, photographs, you agree to pay the cost of replacing the damaged items with equivalent items. After being notified of the claim and given forty eight (48) hours to respond, Food From Friends shall, on behalf of the Member experiencing damages or loss, or any personal or other property located at an Exchange of Food Location, charge the payment to the credit card on file in your Food From Friends Account, and you and the Member expressly authorize Food From Friends to do so. A Member also authorizes Food From Friends to charge the credit card on file in your Food From Friends Account, or otherwise collect payment from you and pursue any avenues available to Food From Friends in this regard, in situations in which you have been determined to have damaged any Exchange of Food Location, including, but not limited to, in relation to any payment requests made by Members, and in relation to any payments made by Food From Friends to Members. If we are unable to charge the credit card on file or otherwise collect payment from you, you agree to remit payment for any damage to the Exchange of Food Location to the applicable Member or to Food From Friends (if applicable).</p>
        <p>Both Locavores and Growers agree to cooperate with and assist Food From Friends in good faith, and to provide Food From Friends with such information and take such actions as may be reasonably requested by Food From Friends, in connection with any complaints or claims made by Members relating to Food or any personal or other property located at an Exchange of Food Location or with respect to any investigation undertaken by Food From Friends or a representative of Food From Friends regarding use or abuse of the Site, Application or the Services. If you are a Member, to the extent you are reasonably able to do so, you agree to participate in mediation or similar resolution process with another Member, at no cost to you, which process will be conducted by Food From Friends or a third party selected by Food From Friends, with respect to losses for which the Member is requesting payment.</p>
        <p>If you are a Member, you understand and agree that Food From Friends or another Member reserves the right, in any of their sole discretion, to make a claim under your homeowner’s, renter’s or other insurance policy related to any damage or loss that you may have caused or been responsible for to an Exchange of Food Location or any personal or other property located at an Exchange of Food Location. You agree to cooperate with and assist Food From Friends in good faith, and to provide Food From Friends with such information as may be reasonably requested by Food From Friends in order to make a claim under your homeowner’s, renter’s or other insurance policy, including, but not limited to, executing documents and taking such further acts as Food From Friends may reasonably request to assist Food From Friends in accomplishing the foregoing.</p>
        <p><b>Member Conduct</b></p>
        <p>In connection with your use of our Site, Application and Services, you may not and you agree that you will not:</p>
        <ul>
        <li> violate any local, state, provincial, national, or other law or regulation, or any order of a court, including, without limitation, zoning restrictions;</li>
        <li> infringe the rights of any person or entity, including without limitation, their intellectual property, privacy, publicity or contractual rights;</li>
        <li> interfere with or damage our Site, Application or Services, including, without limitation, through the use of viruses, cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, packet or IP spoofing, forged routing or electronic mail address information or similar methods or technology;</li>
        <li> use our Site, Application or Services to transmit, distribute, post or submit any information concerning any other person or entity, including without limitation, photographs of others without their permission, personal contact information or credit, debit, calling card or account numbers;</li>
        <li> use our Site, Application or Services in connection with the distribution of unsolicited commercial email (“spam”) or advertisements unrelated to lodging in a private residence;</li>
        <li> “stalk” or harass any other user of our Site, Application, or Services or collect or store any personally identifiable information about any other user other than for purposes of transacting as an Food From Friends Locavore or Grower;</li>
        <li> register for more than one Food From Friends Account or register for a Food From Friends Account on behalf of an individual other than yourself;</li>
        <li> contact a Grower for any purpose other than asking a question related to a request or such Grower’s Food;</li>
        <li> contact a Locavore for any purpose other than asking a question related to a request or such Locavore’s use of the Site, Application and Services;</li>
        <li> when acting as a Locavore or otherwise, recruit or otherwise solicit any Grower or other Member to join third party services or websites that are competitive to Food From Friends, without Food From Friends’s prior written approval;</li>
        <li> impersonate any person or entity, or falsify or otherwise misrepresent yourself or your affiliation with any person or entity;</li>
        <li> use automated scripts to collect information or otherwise interact with the Site, Application, Services or Collective Content;</li>
        <li> use the Site, Application and Services to find a Grower or Locavore and then complete a request of a Food transaction independent of the Site, Application or Services in order to circumvent the obligation to pay any Service Fees related to Food From Friends’s provision of the Services;</li>
        <li> as a Grower, submit any Food with a false or misleading price information, or submit any Food with a price that you do not intend to honor; or</li>
        <li> post, upload, publish, submit or transmit any Content that: (i) infringes, misappropriates or violates a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any other person; or (vii) promotes illegal or harmful activities or substances;</li>
        <li> systematically retrieve data or other content from our Site, Application or Services to create or compile, directly or indirectly, in single or multiple downloads, a collection, compilation, database, directory or the like, whether by manual methods, through the use of bots, crawlers, or spiders, or otherwise;</li>
        <li> use, display, mirror or frame the Site or Application, or any individual element within the Site, Services, or Application, Food From Friends’s name, any Food From Friends trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without Food From Friends’s express written consent;</li>
        <li> access, tamper with, or use non-public areas of the Site or Application, Food From Friends’s computer systems, or the technical delivery systems of Food From Friends’s providers;</li>
        <li> attempt to probe, scan, or test the vulnerability of any Food From Friends system or network or breach any security or authentication measures;</li>
        <li> avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by Food From Friends or any of Food From Friends’s providers or any other third party (including another user) to protect the Site, Services, Application or Collective Content;</li>
        <li> forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Site, Services, Application or Collective Content to send altered, deceptive or false source-identifying information;</li>
        <li> attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Site, Services, Application or Collective Content; or</li>
        <li> copy, store or otherwise access any information contained on the Site, Application, Services or Collective Content for purposes not expressly permitted by these Terms;</li>
        <li> advocate, encourage, or assist any third party in doing any of the foregoing.</li>
        </ul>
        <p>Food From Friends will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. Food From Friends may involve and cooperate with law enforcement authorities in prosecuting users who violate these Terms. You acknowledge that Food From Friends has no obligation to monitor your access to or use of the Site, Application, Services or Collective Content or to review or edit any Member Content, but has the right to do so for the purpose of operating and improving the Site, Application and Services, to ensure your compliance with these Terms, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. Food From Friends reserves the right, at any time and without prior notice, to remove or disable access to any Site Content that Food From Friends, at its sole discretion, considers to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Site, Application or Services. Food From Friends may access, preserve and disclose any of your information if we are required to do so by law, or if we believe in good faith that it is reasonably necessary to (i) respond to claims asserted against Food From Friends or to comply with legal process, (ii) enforce or administer our agreements with users, such as these Terms, (iii) for fraud prevention, risk assessment, investigation, customer support, product development and de-bugging purposes, or (iv) protect the rights, property or safety of Food From Friends, its users, or members of the public.</p>
        <p>Taxes</p>
        <p>As a Grower you are solely responsible for determining your obligations to report, collect, remit or include in your Food Fees any applicable VAT or other sales taxes or income taxes (“Taxes”).</p>
        <p>Tax regulations may require us to collect appropriate Tax information from Growers, or to withhold Taxes from payouts to Growers, or both. If a Grower fails to provide us with documentation that we determine to be sufficient to alleviate our obligation (if any) to withhold Taxes from payouts to you, we reserve the right to freeze all payouts, withhold such amounts as required by law, or to do both, until resolution.</p>
        <p>Food From Friends reserves the right, with prior notice to Growers, to cease the Collection and Remittance in any jurisdiction for any reason at which point Growers and Locavores are once again solely responsible and liable for the collection and/or remittance of any and all Food Taxes, sale Taxes, and income Taxes that may apply in the &nbsp;jurisdiction of the Grower or Locavore.</p>
        <p><b>Privacy</b></p>
        <p>See Food From Friends’s Privacy Policy at <a href="<?= PUBLIC_ROOT . 'info/privacy-policy'; ?>">https://www.foodfromfriends.co/info/privacy-policy/</a> and for information and notices concerning Food From Friends’s collection and use of your personal information.</p>
        <p>&nbsp;</p>
        <p><b>Food From Friends Content and Member Content License</b></p>
        <p>Subject to your compliance with the terms and conditions of these Terms, Food From Friends grants you a limited, non-exclusive, non-transferable license, to (i) access and view any Food From Friends Content solely for your personal and non-commercial purposes and (ii) access and view any Member Content to which you are permitted access, solely for your personal and non-commercial purposes. You have no right to sublicense the license rights granted in this section.</p>
        <p>You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, reverse engineer, broadcast or otherwise exploit the Site, Application, Services, or Collective Content, either by yourself or by anyone on your behalf, in any way or by any means, except as expressly permitted in these Terms. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Food From Friends or its licensors, except for the licenses and rights expressly granted in these Terms.</p>
        <p>You are hereby prohibited from removing or deleting any and all copyright notices, restrictions and signs indicating proprietary rights of Food From Friends, including copyright mark [©] or trademark [® or ™] contained in or accompanying the content included in the Services, and you represent and warrant that you will abide by all applicable laws in this respect. You are further prohibited from using, diluting or staining any name, mark or logo that is identical, or confusingly similar to any of Food From Friends’s marks and logos, whether registered or not.</p>
        <p>&nbsp;</p>
        <p><b>Member Content</b></p>
        <p>We may, in our sole discretion, permit Members to post, upload, publish, submit or transmit Member Content. By making available any Member Content on or through the Site, Application and Services, you hereby grant to Food From Friends a worldwide, irrevocable, perpetual, non-exclusive, transferable, assignable, royalty-free license, with the right to sublicense, to use, view, reproduce, copy, adapt, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, access, view, and otherwise exploit such Member Content in connection with Food From Friends , whether through the Internet, any mobile device or otherwise, in any media formats and through any media channels known today and developed in the future.</p>
        <p>You acknowledge and agree that you are solely responsible for all Member Content that you make available through the Site, Application and Services. Accordingly, you represent and warrant that: (i) you either are the sole and exclusive owner of all Member Content that you make available through the Site, Application and Services or you have all rights, licenses, consents and releases that are necessary to grant to Food From Friends the rights in such Member Content, as contemplated under these Terms; and (ii) neither the Member Content nor your posting, uploading, publication, submission or transmittal of the Member Content or Food From Friends’s use of the Member Content (or any portion thereof) on, through or by means of the Site, Application and the Services will infringe, misappropriate or violate a third party’s patent, copyright, trademark, trade secret, moral rights or other proprietary or intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</p>
        <p>You agree that Food From Friends may remove at any time any Member Content you have uploaded to Food From Friends in its sole discretion with or without any reason.</p>
        <p>&nbsp;</p>
        <p><b>Links</b></p>
        <p>The Site, Application and Services may contain links to third-party websites or resources. You acknowledge and agree that Food From Friends is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by Food From Friends of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources or the Content, products or services on or available from such websites or resources.</p>
        <p><b>Ownership</b></p>
        <p>The Site, Application, Services, and Collective Content are protected by copyright, trademark, and other laws of the United States and foreign countries. You acknowledge and agree that the Site, Application, Services and Collective Content, including all associated intellectual property rights is the exclusive property of Food From Friends and its licensors. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Site, Application, Services, or Collective Content.</p>
        <p><b>Proprietary Rights Notices</b></p>
        <p>All trademarks, service marks, logos, trade names and any other proprietary designations of Food From Friends used herein are trademarks or registered trademarks of Food From Friends. Any other trademarks, service marks, logos, trade names and any other proprietary designations are the trademarks or registered trademarks of their respective parties.</p>
        <p><b>Feedback</b></p>
        <p>We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Site, Application and Services (“Feedback”). You may submit Feedback by emailing us at foodfromfriendsco@gmail.com section of the Site and Application. You acknowledge and agree that all Feedback will be the sole and exclusive property of Food From Friends and you hereby irrevocably assign to Food From Friends and agree to irrevocably assign to Food From Friends all of your right, title, and interest in and to all Feedback, including without limitation all worldwide patent, copyright, trade secret, moral and other proprietary or intellectual property rights therein. At Food From Friends’s request and expense, you will execute documents and take such further acts as Food From Friends may reasonably request to assist Food From Friends to acquire, perfect, and maintain its intellectual property rights and other legal protections for the Feedback.</p>
        <p><b>Termination, Suspension and Food From Friends Account Cancellation</b></p>
        <p>We may, in our discretion and without liability to you, with or without cause, with or without prior notice and at any time: (a) terminate or suspend these Terms or your access to our Site, Application and Services, and (b) deactivate or cancel your Food From Friends Account. Upon termination or suspension, we will promptly pay you any amounts we reasonably determine we owe you in our discretion, which we are legally obligated to pay you. In the event Food From Friends terminates or suspends these Terms, or your access to our Site, Application and Services or deactivates or cancels your Food From Friends Account you will remain liable for all amounts due hereunder. You may cancel your Food From Friends Account at any time via the “Cancel Account” feature of the Services or by sending an email to foodfromfriendsco@gmail.com. Please note that if your Food From Friends Account is cancelled, we do not have an obligation to delete or return to you any Content you have posted to the Site, Application and Services, including, but not limited to, any reviews or Feedback.</p>
        <p><b>Copyright Policy</b></p>
        <p>Food From Friends respects copyright law and expects its users to do the same. It is Food From Friends’s policy to terminate in appropriate circumstances the Food From Friends Accounts of Members or other account holders who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders.</p>
        <p><b>Disclaimers</b></p>
        <p>IF YOU CHOOSE TO USE THE SITE, APPLICATION , SERVICES, YOU DO SO AT YOUR SOLE RISK. YOU ACKNOWLEDGE AND AGREE THAT FOOD FROM FRIENDS DOES NOT CONDUCT BACKGROUND CHECKS ON ANY MEMBER, INCLUDING, BUT NOT LIMITED TO, LOCAVORES AND GROWERS. THE SITE, APPLICATION, SERVICES, COLLECTIVE CONTENT AND REFERRAL PROGRAM ARE PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, FOOD FROM FRIENDS EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. FOOD FROM FRIENDS MAKES NO WARRANTY THAT THE SITE, APPLICATION, SERVICES, COLLECTIVE CONTENT, INCLUDING, BUT NOT LIMITED TO, THE FOOD, OR ANY REFERRAL PROGRAM WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. FOOD FROM FRIENDS MAKES NO WARRANTY REGARDING THE QUALITY OF ANY FOOD, THE SERVICES OR COLLECTIVE CONTENT OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY COLLECTIVE CONTENT OBTAINED THROUGH THE SITE, APPLICATION, SERVICES OR REFERRAL PROGRAM.</p>
        <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM FOOD FROM FRIENDS OR THROUGH THE SITE, APPLICATION, SERVICES OR COLLECTIVE CONTENT, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
        <p>YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE, APPLICATION OR SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE, APPLICATION OR SERVICES, INCLUDING, BUT NOT LIMITED TO, ANY GROWERS OR LOCAVORES. YOU UNDERSTAND THAT FOOD FROM FRIENDS DOES NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE SITE, APPLICATION OR SERVICES OR TO REVIEW ANY FOOD. FOOD FROM FRIENDS MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE SITE, APPLICATION OR SERVICES OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS OF THE SITE, APPLICATION OR SERVICES. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE, APPLICATION OR SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE, APPLICATION OR SERVICES, INCLUDING, BUT NOT LIMITED TO, LOCAVORES AND GROWERS, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON.</p>
        <p><b>Limitation of Liability</b></p>
        <p>YOU ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ENTIRE RISK ARISING OUT OF YOUR ACCESS TO AND USE OF THE SITE, APPLICATION, SERVICES AND COLLECTIVE CONTENT, AND YOUR FOOD OR REQUEST OF ANY FOOD VIA THE SITE, APPLICATION AND SERVICES, AND YOUR PARTICIPATION IN ANY REFERRAL PROGRAM AND ANY CONTACT YOU HAVE WITH OTHER USERS OF FOOD FROM FRIENDS WHETHER IN PERSON OR ONLINE REMAINS WITH YOU. NEITHER &nbsp;FOOD FROM FRIENDS NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SITE, APPLICATION, SERVICES, COLLECTIVE CONTENT OR ANY REFERRAL PROGRAM WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE PRODUCTS OR SERVICES, OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, FROM THE USE OF OR INABILITY TO USE THE SITE, APPLICATION, SERVICES OR COLLECTIVE CONTENT, FROM ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER USERS OF THE SITE, APPLICATION, OR SERVICES OR OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE, APPLICATION, SERVICES, OR YOUR PARTICIPATION IN ANY REFERRAL PROGRAM OR FROM YOUR FOOD OR REQUEST OF ANY FOOD VIA THE SITE, APPLICATION AND SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT FOOD FROM FRIENDS HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</p>
        <p>IN NO EVENT WILL FOOD FROM FRIENDS’S AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS AND YOUR USE OF THE SITE, APPLICATION AND SERVICES INCLUDING, BUT NOT LIMITED TO, FROM YOUR FOOD OR REQUEST OF ANY FOOD VIA THE SITE, APPLICATION AND SERVICES, OR FROM THE USE OF OR INABILITY TO USE THE SITE, APPLICATION, SERVICES, OR COLLECTIVE CONTENT OR YOUR PARTICIPATION IN ANY REFERRAL PROGRAM AND IN CONNECTION WITH ANY FOOD OR INTERACTIONS WITH ANY OTHER MEMBERS, EXCEED THE AMOUNTS YOU HAVE PAID OR OWE FOR REQUEST VIA THE SITE, APPLICATION AND SERVICES AS A MEMBER WHO IS A LOCAVORE &nbsp;IN THE SIX (6) MONTH PERIOD PRIOR TO THE EVENT GIVING RISE TO THE LIABILITY, OR IF YOU ARE A MEMBER WHO IS A GROWER, THE AMOUNTS PAID BY &nbsp;FOOD FROM FRIENDS TO YOU IN THE SIX (6) MONTH PERIOD PRIOR TO THE EVENT GIVING RISE TO THE LIABILITY, OR ONE HUNDRED DOLLARS ($100), IF NO SUCH PAYMENTS HAVE BEEN MADE, AS APPLICABLE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN FOOD FROM FRIENDS AND YOU.</p>
        <p>&nbsp;</p>
        <p><b>Assignment</b></p>
        <p>You may not assign or transfer these Terms, by operation of law or otherwise, without Food From Friends’s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. Food From Friends may assign or transfer these Terms, at its sole discretion, without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
        <p><b>Notices</b></p>
        <p>Any notices or other communications permitted or required hereunder, including those regarding modifications to these Terms, will be in writing and given by Food From Friends (i) via email (in each case to the address that you provide) or (ii) by posting to the Site or via the Application. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
        <p><b>Reporting Misconduct</b></p>
        <p>If the Grower or Locavore is acting or has acted inappropriately, including but not limited to, anyone who (i) engages in offensive, violent or sexually inappropriate behavior, (ii) you suspect of stealing from you, or (iii) engages in any other disturbing conduct, you should immediately report such person to the appropriate authorities and then to Food From Friends by contacting us with your police station and report number at foodfromfriendsco@gmail.com; provided that your report will not obligate us to take any action beyond that required by law (if any) or cause us to incur any liability to you.</p>
        <p><b>Indemnification</b></p>
        <p>You agree to release, defend, indemnify, and hold Food From Friends and its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (a) your access to or use of the Site, Application, Services, or Collective Content or your violation of these Terms; (b) your Member Content; and (c) your (i) interaction with any Member, (ii) request of Food, (iii) creation of Item, (iv) the use, condition or rental of Food by you, including, but not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of a rental, request or use of Food, or (v) injuries, damages or other claims to any persons in the use of Food.</p>
        <p><b>Entire Agreement</b></p>
        <p>These Terms constitute the entire and exclusive understanding and agreement between Food From Friends and you regarding the Site, Application, Services, Collective Content, and any request of Food made via the Site, Application and Services, and these Terms supersede and replace any and all prior oral or written understandings or agreements between Food From Friends and you regarding request of Food, the Site, Application, Services, and Collective Content.</p>
        <p><b>Governing Law</b></p>
        <p>Your use of the Services and these Terms shall be governed by, and construed in accordance with, the internal laws of the United States of America as well as the State that the Exchange Of Food occurs without reference to the choice of law or conflicts of law principles thereof, and all claims relating to or arising out of your use of the Service or these Terms, or the breach thereof, whether sounding in contract, tort or otherwise, shall likewise be governed by the laws of the State the Exchange Of Food occurs without reference to the choice of law or conflicts of law principles thereof. &nbsp;</p>
        <p><b>Disputes</b></p>
        <p>Any dispute, claim or controversy arising out of or relating to the Services or these Terms, or the breach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by a panel of neutral arbitrators, unless the matter in controversy is within the scope of an applicable small claims court’s jurisdiction. The arbitration shall be administered by JAMS pursuant to its Comprehensive Arbitration Rules and Procedures. Judgment on the arbitration award may be entered in any court having jurisdiction. This clause shall not preclude Mode or you from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction. Note that there is no judge or jury in an arbitration proceeding and the decision of the arbitrator shall be binding upon both parties.</p>
        <p><b>General</b></p>
        <p>The failure of Food From Friends to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Food From Friends. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise. If for any reason an arbitrator or a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
        <p><b>Contacting Food From Friends</b></p>
        <p>If you have any questions about these Terms, please contact Food From Friends at foodfromfriendsco@gmail.com.</p>
    </div>
</main>